[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "/"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true
