[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://13.209.13.101/:splat"
  status = 200
  force = true
