[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "http://13.209.13.101"

[[redirects]]
  from = "/api/*"
  to = "http://13.209.13.101/:splat"
  status = 200
  force = true
